# Generated by Django 5.2.17 on 2026-09-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='ciudad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='telefono',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='asunto',
            field=models.CharField(default='Contacto web', max_length=180),
        ),
    ]
