# Generated by Django 5.2.17 on 2026-09-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_contactmessage_ciudad_contactmessage_edad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=180)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_user', models.EmailField(blank=True, max_length=254)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
