# Generated by Django 5.2.17 on 2026-09-13 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('modalidad', models.CharField(choices=[('figuras', 'Figuras / Kata'), ('combate', 'Combate / Kumite'), ('defensa', 'Defensa Personal')], max_length=20)),
                ('edad_min', models.PositiveSmallIntegerField(default=0)),
                ('edad_max', models.PositiveSmallIntegerField(default=99)),
                ('sexo', models.CharField(default='Mixto', max_length=20)),
                ('rango_cintas', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('sede_lugar', models.CharField(max_length=180)),
                ('estado', models.CharField(max_length=80)),
                ('estatus', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado')], default='programado', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='deporte.atleta')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='competencia.categoria')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='competencia.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda', models.PositiveSmallIntegerField(default=1)),
                ('puntos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones', to='competencia.inscripcion')),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puntuaciones', to='deporte.arbitro')),
            ],
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('evento', 'atleta', 'categoria'), name='unique_evento_atleta_categoria'),
        ),
    ]
