# Generated by Django 5.2.17 on 2026-09-13 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=30, unique=True)),
                ('nivel_rango', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Asociacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('estado', models.CharField(max_length=80)),
                ('presidente', models.CharField(blank=True, max_length=140)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='asociaciones/')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('entrenador_principal', models.CharField(blank=True, max_length=140)),
                ('ciudad_municipio', models.CharField(max_length=100)),
                ('asociacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clubes', to='deporte.asociacion')),
            ],
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=30, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('cinturon_kyu', models.CharField(max_length=80)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='atletas/')),
                ('activo', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atletas', to='deporte.club')),
            ],
        ),
    ]
